---
- hosts: meraki_servers
  vars:
    network_id: "XXXXXXXXXXXXXXXXXX" # Put your Network ID here
  gather_facts: false
  tasks:
    - name: Enable Vlans on the MX
      cisco.meraki.networks_appliance_vlans_settings:
        state: present
        networkId: "{{network_id}}"
        vlansEnabled: true
        
    - name: Update appliance traffic shaping
      cisco.meraki.networks_appliance_traffic_shaping:
        state: present
        globalBandwidthLimits:
          limitDown: 5120
          limitUp: 2048
        networkId: "{{network_id}}"

    - name: Create FW outbound L3 rules
      cisco.meraki.networks_appliance_firewall_l3_firewall_rules:
        networkId: "{{network_id}}"
        state: present
        rules:
          - comment: Block malicious site
            destCidr: internetbadguys.com
            destPort: any
            policy: deny
            protocol: any
            srcCidr: any
            syslogEnabled: false
    
    - name: Create Corp VLAN
      cisco.meraki.networks_appliance_vlans:
        state: present
        applianceIp: "192.168.100.1"
        vlanId: "100"
        id: "100"
        ipv6:
          enabled: false
        name: "Corporate VLAN"
        networkId: "{{network_id}}"
        subnet: "192.168.100.0/24"
      
    - name: Create Guest VLANs
      cisco.meraki.networks_appliance_vlans:
        state: present
        applianceIp: "192.168.200.1"
        vlanId: "200"
        id: "200"
        ipv6:
          enabled: false
        name: "Guest VLAN"
        networkId: "{{network_id}}"
        subnet: "192.168.200.0/24"
        
    - name: Activate Anti-Malware
      cisco.meraki.networks_appliance_security_malware:
        state: present
        networkId: "{{network_id}}"
        mode: "enabled"

    - name: Activate IPS
      cisco.meraki.networks_appliance_security_intrusion:
        state: present
        idsRulesets: "balanced"
        mode: "prevention"
        networkId: "{{network_id}}"